### ISSUE TITLE
Error encountered using virtual function of 82599

### ISSUE THREAD

**Issue by haris00** [emmericp/MoonGen#104] opened 2015-11-07 14:13 UTC
Hi,
I have binded the following two virtual functions of 82599 with dpdk inside a VM
00:05.0 Ethernet controller [0200]: Intel Corporation 82599 Ethernet Controller Virtual Function [8086:10ed] (rev 01)
00:06.0 Ethernet controller [0200]: Intel Corporation 82599 Ethernet Controller Virtual Function [8086:10ed] (rev 01)

They are binded succesfully by ./build.sh script. However when I run the following script:
"./build/MoonGen ./examples/quality-of-service-test.lua 0 1"
I get the error:

[INFO]  Found 2 usable devices:
   Device 0: 02:09:C0:E8:20:7F (unknown NIC (PCI ID 8086:10ed))
   Device 1: 02:09:C0:C4:B1:18 (unknown NIC (PCI ID 8086:10ed))
[FATAL] Lua error in task master
lua/include/device.lua:190: Could not configure device 0: error -22
Stack Traceback
===============
(2) Lua method 'fatal' at file 'lua/include/log.lua:129'
        Local variables:
         self = table: 0x4117e870  {DEBUG:0, fatal:function: 0x41178138, writeToLog:function: 0x41170280, INFO:1 (more...)}
         str = string: "Could not configure device 0: error -22"
(3) Lua field 'config' at file 'lua/include/device.lua:190'
        Local variables:
         args = table: 0x40b285d0  {rxQueues:1, rssNQueues:0, speed:0, dropEnable:true, txDescs:256, txQueues:3 (more...)}
         rss_enabled = number: 0
         rc = number: -22
(4) Lua function 'master' at file './examples/quality-of-service-test.lua:40' (best guess)
        Local variables:
         txPort = number: 0
         rxPort = number: 1
         bgRate = number: 1500
         fgRate = number: 100
         txDev = nil
         rxDev = nil
(5) global C function 'xpcall'
(6) Lua upvalue 'slave' at file 'lua/include/main.lua:89'
        Local variables:
         _ = string: "./build/MoonGen"
         file = string: "./examples/quality-of-service-test.lua"
         devices = table: 0x419409e8  {1:table: 0x41940b30, 2:table: 0x41940ea0}
         args = table: 0x41941288  {1:0, 2:1}
(7) Lua function 'main' at file 'lua/include/main.lua:125' (best guess)
        Local variables:
         task = string: "master"
        lua/include/device.lua:190: Could not configure device 0: error -22

Why is that? Can you please comment

Regards
Haris

**Comment by emmericp** [comment] 2015-11-07 19:03
Some of MoonGens defaults are probably incompatible with the VF.

Better support for VFs is on my todo list.

**Comment by emmericp** [comment] 2015-11-07 19:16
Can you use PFs instead of VFs?

VFs also come with other problems: for example, hardware timestamping is not supported by 82599 VFs.

**Comment by haris00** [comment] 2015-11-07 19:21
No, because in my case it has to be multiple VMs each containing instance of MoonGen for stress testing purposes. I only have two physical functions where as many virtual functions. So physical function would limit the number of MoonGen instances i can spawn.
I am not much concerned with hardware timestamping. All i need is that i am able to send packets to a address and receive those packets back, thats it

**Comment by emmericp** [comment] 2015-11-07 19:52
Okay, I just tested this: the problem is the number of TX queues (3) that this script tries to use, this is too much for the vf.

But it looks like you aren't going to need that many tx queues, so you should be fine.

However, MoonGen currently supports neither rate control nor device-based statistics for VFs. The former can be emulated with software like other packet generators do (just sleep), the latter can easily be fixed with manual counters.

I suggest to look at benchmark/upd-throughput.lua. This script works fine with VFs except that the transmit stats tracking doesn't work. But that can be fixed by replacing the device-based tx counter with a "manu"l tx counter. See quality-of-service-test.lua for an example of a manual tx counter.


You probably want to write your own script for this anyways, so this shouldn't be a problem.

**Closed** 2016-02-14 22:40 UTC
