### ISSUE TITLE
Which vNIC will be supported by Moongen?

### ISSUE THREAD

**Issue by Binghankina** [emmericp/MoonGen#126] opened 2016-05-12 09:44 UTC
Hi,

I want to run Moongen in a virtual environment. I constantly got following:
error lua/include/device.lua:180: could not configure device 0: error -22

The I find that the reason is that our Virtio driver is not supported by Moongen. Do you know whether Moongen will support advanced driver like VFIO? Or do you have any plan for virtual environment.

BRs,
Binghan

**Comment by emmericp** [comment] 2016-05-12 10:33
The problem here is probably that we try to configure filters that are not supported by VirtIO. This will be fixed with the new IO abstraction layer we are working on.
We plan to support both VirtIO and VFIO, with the latter being the better option.

**Comment by Binghankina** [comment] 2016-05-12 12:01
Thanks for your answer. My last question is that can you share you time plan? Since we need a good traffic generator which can be run on a VM, if it takes too long time for Moongen to support virtual environment, then we may need to consider other options.

**Comment by emmericp** [comment] 2016-08-15 10:00
our new IO backend (soon to be used in MoonGen) is way more device-independent, check out https://github.com/Phobos-Framework/phobos

currently tested with virtio

**Comment by emmericp** [comment] 2016-08-27 22:49
virtio works in https://github.com/emmericp/MoonGen/commit/4353d3e3e554498d0ee66013e06f7dd3773c1d92

**Closed by emmericp** 2016-08-27 22:49 UTC

**Comment by Binghankina** [comment] 2016-08-28 00:44
Thanks a lot. I will try it.

**Comment by hopoaat** [comment] 2017-02-23 09:54
Hi!

I've tried MoonGen from VM, but MG can't control the rate limit for the virtio NIC. Is there any solution to control the rate with software, or with hardware rate control?
Now I got constant rate with hardware rate control no matter what mpps speed I give for the script, software rate control doesn't even work for me.
I' ve tried to use the examples/benchmark/compare-rate-control-mechanisms.lua script, and when the script want to switch to software rate control, I get the following error message:
"...loud/MoonGen/build/../libmoon/../lua/crc-ratecontrol.lua:22: attempt to index global 'log' (a nil value)"
I use igb_uio driver in the VM for the Virtio NIC.

Can you help me to investigate this problem?

Br,

Peter

**Comment by emmericp** [comment] 2017-02-23 11:00
CRC rate control can't work by design in a VM. "Hardware" rate control isn't supported by virtio (on the VM side).
The error you are encountering happens while trying to show the actual error message, I'll fix that.

Other than that, you should try `examples/rate-control-methods.lua` which offers normal software rate control.
The script you are trying to use is for a specific test setup in the paper

**Comment by hopoaat** [comment] 2017-02-24 09:49
Hi! 

Thanks for your answer, really appreciat it. It's working. 
My observation is that the maximum throughput with cbr traffic is about 8.5mpps(60byte packets). Is it a limitation?
Can I achive the max. line rate throughput(60byte packets 14+mpps) for the virtio interface?
Poisson can achive about 5.5mpps.(Sadly, no matter, if I use multiqueue/multithread on the interface with Poisson, the throughput not changing.)
Can you give me a link to the documentation, where I can find answer for my questions?
/May I open new thread for this question?/ 

Br,

Peter

**Comment by emmericp** [comment] 2017-02-24 11:10
virtio is unfortunately somewhat limiting here on the hypervisor side :(

5.5 mpps is already faster than I'd have guessed, what hypervisor/network are you using?

**Comment by hopoaat** [comment] 2017-02-28 12:10
Hi!

Sorry for the late reply.
I'm using qemu 2.5,libvirt 1.3.1, and OVS+DPDK on the host.
As I observed with other dpdk tools, the virtio i/f can achive more than 8mpps without problem.
It could be good, if I can use multiqueue support in the VM, so I can reach the theoretical speed.
I'd reached it with testpmd  in the vm, and multiqueue support enabled on host, and for the vhostuser interface. Generated data stream with MoonGen from other server, and loop back the traffic with testpmd. MoonGen measured ~14mpps on the rx side.(Almost hit the virtio i/f link speed.)
Here is a topology:
MoonGen TG(tx0) -> ToR Switch -> Echo Server(OVS-DPDK with multiqueue enabled) -> VM (testpmd-multiqueue-loopback) -> Echo Server(OVS-DPDK with multiqueue enabled) -> ToR Switch -> MoonGen TG(rx0).
Multiqueue worked because of the RSS on PHY nic at Echo side, so I just had to generate multiple flows with MoonGen.
So my question: Can I use multiqueue feature on the virtio interface in the VM, or how should I achive the max. link speed?
Really thanks for your help!

Br,

Peter

**Comment by emmericp** [comment] 2017-02-28 13:06
I haven't tried to use RX MQ in this setup yet, I'm not sure how it interacts with RSS on the hypervisor in this scenario but it should work.
Multi-queue in the TX direction should just work out-of-the-box.

The poor tx performance you are seeing is likely because MoonGen does "proper" CBR traffic and sends individual packets instead of bursts, this can limit the performance (even on real hardware, I can't get more than ~12 Mpps on an 82599 with this approach).

Can you test the tx performance with the `examples/benchmark/udp-throughput.lua` script? The parameters are a list of `<portid>:<tx queues/cores>`. This script will send 256 flows without any rate control.

**Comment by hopoaat** [comment] 2017-03-29 12:59
Hi!

Sorry for the big delay, but got stuffs to do. I'll check that script, but I've a more important question.
Did you observe mass packet drop(all pkt on rx side) with Intel 82599 NIC when you received a higher frame than 1514?
I use that NIC's 1 port for Tx/Rx. The traffic goes a round trip, like this:

Nic,tx->eXtreme SW->Server->VM1(loopbak)->Server->eXtreme SW->Nic,rx
Until Nic.rx state I can see the counters(in eXtreme too), and seems like it's ok. The eXtreme forward the traffic, but I can detect 0 pkts counting with MoonGen.
- I use hardware rate controll
- The port configuration seems like this now:

--Port setup----------------------
local txDev = device.config{ port = args.txDev, rxQueues = args.queues, txQueues = args.queues}
local rxDev
if args.rxDev == args.txDev then
    rxDev = txDev
else
    rxDev = device.config{ port = args.rxDev, rxQueues = args.queues }
-------------------------------------
-The counting task something like this:

function counterSlave(queue)
        local rxStats = stats:newDevRxCounter(queue, "plain")
        while mg.running and runtime:running() do
                      local rx = queue : tryRecv ( bufs , 100 )
                      --Algorithm on packets here
                      rxStats:update()
                      bufs:freeAll()
        end
        rxStats:finalize()
end

Did I miss something? /Tried with dropEnable = false - not helped/ 
Any suggestion?

Thanks for your help!

Br,

Peter
