### ISSUE TITLE
More mlx5 issues

### ISSUE THREAD

**Issue by JelteF** [emmericp/MoonGen#142] opened 2016-06-23 10:17 UTC
I'm having more SEG_FAULTS. 
This one is caused by these lines:
https://github.com/emmericp/MoonGen/blob/master/lua/include/device.lua#L635-L640

**Comment by JelteF** [comment] 2016-06-23 10:20
I also get this warning when running lacp.lua:
```
PMD: librte_pmd_mlx5: 0x799f20: filter type (2) not supported
[WARN]  l2 filter error: -22
```

**Comment by emmericp** [comment] 2016-06-23 11:00
Ah yes, more bad code that just assumes everything is an Intel NIC :/
For now: comment out https://github.com/emmericp/MoonGen/blob/master/lua/include/device.lua#L294


I'm currently working on a refactoring of the whole abstraction layer that will fix stuff like this.


The warning seems to be caused by the LACP implementation - it uses a L2 ethertype filter to handle LACPDUs in a separate thread.
You won't be able to use the ARP and LACP implementations in MoonGen if this filter isn't supported by the DPDK mlx driver.

**Comment by emmericp** [comment] 2016-08-27 22:46
fixed in https://github.com/emmericp/MoonGen/commit/4353d3e3e554498d0ee66013e06f7dd3773c1d92

**Closed by emmericp** 2016-08-27 22:46 UTC
